# Site settings
title: Geeky Stuff
email: vijay.sali@gmail.com
description: "Geek, Tech savvy,Web developer, Google Fan boy, interested to learn new things,Ambitious ..."
baseurl: ""
url: "vijaysali.in"

# Build settings
markdown: kramdown
permalink: pretty
username: vijaysali
firstname: VIJAYSALI 
my_address: "From Dharwad ,Lives in Bangalore -KA , INDIA"