# Site settings
title: Dev-vijay, Personal blog...
email: vijay.sali@gmail.com
description: ""
baseurl: ""
url: "vijaysali.in"

# Build settings
markdown: kramdown
permalink: pretty
username: vijaysali
firstname: VIJAYSALI
my_address: "From Dharwad ,Lives in Bangalore -KA , INDIA"
